apiVersion: v1
kind: Secret
metadata:
  name: reliefgrid-secret
  namespace: reliefgrid
type: Opaque
stringData:
  POSTGRES_USER: "reliefuser"
  POSTGRES_PASSWORD: "reliefpassword"
  POSTGRES_DB: "reliefgrid"
  DATABASE_URL: "postgresql://reliefuser:reliefpassword@postgres:5432/reliefgrid"
  REDIS_URL: "redis://redis:6379/0"
